### ISSUE TITLE
pts files

### ISSUE THREAD

**Issue by xiyichen** [YuYin1/JASRNet#3]
I'm trying to train a model on CelebA dataset but it requires pts files. I'm not sure what these files are and how to generate them. Please specify.

**Comment by YuYin1** [comment]
pts files are the landmark labels of each dataset. The path could be set in the ` src/data/celeba.py `:

**Comment by YuYin1** [comment]
pts files are the landmark labels of each dataset. The path could be set in the src/data/celeba.py:
`self.dir_anno = os.path.join(self.apath, 'CelebA_train_HR')` (line35)

**Comment by xiyichen** [comment]
Thank you for your reply. I generated 68 landmarks for each image using dlib. It is running now, but all I've got is nan. Do you know what might have caused the problem?
<img width="278" alt="WeChat Screenshot_20200526001804" src="https://user-images.githubusercontent.com/50854238/82829785-af5d1080-9ee6-11ea-8e78-3858f7cf1df3.png">

**Comment by YuYin1** [comment]
It seems that the data is not correctly loaded.

**Comment by xiyichen** [comment]
Thank you. I have fixed it and have successfully trained models. Now I have some surveillance faces that are originally in low-resolution (like 30x30) that I want to test out. Since they are not downsampled, I don't have hr images or landmark annotations. Is it possible to test solely on lr images?

**Comment by YuYin1** [comment]
You can modify the dataloader and set the HR, and landmark annotations to None. Then run `python main.py --save test_folder **--test_only** --save_results --save_gt --pre_train PATH_TO_YOUR_MODEL`

**Comment by YuYin1** [comment]
You can modify the dataloader and set the HR, and landmark annotations to None. Then run python main.py --save test_folder --test_only --save_results --save_gt --pre_train PATH_TO_YOUR_MODEL
